name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Ejecuta el workflow cuando se haga un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuración de AWS CLI con credenciales "hardcoded"
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Lanza la instancia EC2 y despliega el código
      - name: Launch EC2 instance and deploy code
        run: |
          # Variables
          AMI_ID="ami-0c02fb55956c7d316" # Amazon Linux 2 en us-east-1
          INSTANCE_TYPE="t2.micro"
          KEY_NAME="MiClave"  # Reemplaza con el nombre de tu clave SSH
          SECURITY_GROUP="default"
          
          # Crear un grupo de seguridad
          SG_ID=$(aws ec2 create-security-group --group-name $SECURITY_GROUP --description "Security group for web server" --query 'GroupId' --output text)
          aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 22 --cidr 0.0.0.0/0
          aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 80 --cidr 0.0.0.0/0

          # Lanza la instancia EC2
          INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --count 1 --instance-type $INSTANCE_TYPE --key-name $KEY_NAME --security-group-ids $SG_ID --query 'Instances[0].InstanceId' --output text)

          # Espera a que la instancia esté lista
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

          # Obtén la IP pública de la instancia
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)

          # Conéctate por SSH y despliega el código
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/MiClaveEC2.pem ec2-user@$PUBLIC_IP << EOF
            sudo yum update -y
            sudo yum install -y git httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            cd /var/www/html
            git clone https://github.com/Loony213/PaginaYaml .
          EOF

          echo "Application deployed at http://$PUBLIC_IP"
